// <auto-generated />
using EventGradingSystem.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace EventGradingSystem.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230413181824_EventMarksCreate")]
    partial class EventMarksCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("EventGradingSystem.Database.Entities.ExpertGrade", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GradeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GradeValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identifier");

                    b.ToTable("ExpertGrades");
                });

            modelBuilder.Entity("EventGradingSystem.Database.Entities.ExpertNote", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.ToTable("ExpertNotes");
                });

            modelBuilder.Entity("EventGradingSystem.Database.Entities.ParticipantGrade", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GradeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GradeValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identifier");

                    b.ToTable("ParticipantGrades");
                });

            modelBuilder.Entity("EventGradingSystem.Database.Entities.ParticipantNote", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.ToTable("ParticipantNotes");
                });

            modelBuilder.Entity("EventGradingSystem.Database.Entities.ParticipationMark", b =>
                {
                    b.Property<string>("ParticipantId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParticipantId", "EventTypeId", "EventId");

                    b.ToTable("ParticipationMarks");
                });

            modelBuilder.Entity("EventGradingSystem.Database.Entities.SpecialMark", b =>
                {
                    b.Property<string>("ParticipantId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParticipantId", "EventTypeId", "EventId");

                    b.ToTable("SpecialMarks");
                });
#pragma warning restore 612, 618
        }
    }
}
