// <auto-generated />
using ConventionGradingSystem.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConventionGradingSystem.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231016114243_ConfigurationIdentifiersTypeChange")]
    partial class ConfigurationIdentifiersTypeChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("ConventionGradingSystem.Database.Entities.ExpertGrade", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CriterionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GradeValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identifier");

                    b.ToTable("ExpertGrades");
                });

            modelBuilder.Entity("ConventionGradingSystem.Database.Entities.ExpertNote", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.ToTable("ExpertNotes");
                });

            modelBuilder.Entity("ConventionGradingSystem.Database.Entities.ParticipantGrade", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CriterionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GradeValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Identifier");

                    b.ToTable("ParticipantGrades");
                });

            modelBuilder.Entity("ConventionGradingSystem.Database.Entities.ParticipantNote", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.ToTable("ParticipantNotes");
                });

            modelBuilder.Entity("ConventionGradingSystem.Database.Entities.ParticipationMark", b =>
                {
                    b.Property<string>("ParticipantId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.HasKey("ParticipantId", "ContestId", "EventId");

                    b.ToTable("ParticipationMarks");
                });

            modelBuilder.Entity("ConventionGradingSystem.Database.Entities.SpecialMark", b =>
                {
                    b.Property<string>("ParticipantId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.HasKey("ParticipantId", "ContestId", "EventId");

                    b.ToTable("SpecialMarks");
                });
#pragma warning restore 612, 618
        }
    }
}
